install.packages(c("jSonarR"," R.cache","R.rsp","V8", "jsonlite","RCurl","bitops") ,dependencies = TRUE)
library(RCurl)
library(R.cache)
#library(jSonarR)
#library(jsonlite)
library(V8)
library(R.rsp)
library(RCurl)
library(bitops)

library(jsonlite)
install.packages("jsonlite",dependencies = TRUE)
library(jsonlite)

sessionInfo()
packrat::set_opts(external.packages = c("rstudio"))
devtools::install_github("jeroenooms/jsonlite")
.libPaths("C:/Users/Rohit Jaladi/Documents/R/win-library/3.2") 
.libPaths()
.libPaths("C:/Users/Rohit Jaladi/AppData/Local/Temp/RtmpkhqNE5/downloaded_packages")
Sys.getenv("R_LIBS_USER")
p_unlock()

install.packages("jsonlite",dependencies = TRUE)
install.packages("jsonld",dependencies = TRUE)
library(jsonvalidate)
library("jsonlite")
library("rjson")
library(jSonarR)
library(jsonld)
list.files('./')
getwd()

result <- fromJSON("sample1.json")

